name: Docs

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Docs
    defaults:
      run:
        working-directory: .
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install ubuntu packages
      run: sudo apt-get update
    - name: Install requirements
      run: pip install -r requirements.txt
    - name: Docs
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_Key }}
        script: cd /root/reinspy; git pull; bash /root/reinspy/docs/build_docs.sh
